#!/data/data/com.termux/files/usr/bin/bash
# Enable cron + boot autostart + wake-lock. Idempotent.
set -euo pipefail

HERE="$(dirname "$(readlink -f "$0")")"
CONF="$HOME/.config/hidock-sync/config"
[ -f "$CONF" ] || { echo "config missing at $CONF — run setup.sh first"; exit 2; }
. "$CONF"
INTERVAL=${CRON_INTERVAL_MIN:-30}

# 1) Boot script: starts crond and grabs a wake-lock when the phone boots.
mkdir -p "$HOME/.termux/boot"
cat > "$HOME/.termux/boot/start-crond" <<EOF
#!/data/data/com.termux/files/usr/bin/sh
termux-wake-lock
crond
EOF
chmod +x "$HOME/.termux/boot/start-crond"
echo "boot script: $HOME/.termux/boot/start-crond"

# 2) Crontab: every \$INTERVAL minutes, run the sync.
mkdir -p "$HOME/.config/cron"
CRON_FILE="$HOME/.config/cron/crontab"
cat > "$CRON_FILE" <<EOF
# Generated by hidock-android-sync setup-cron.sh
*/${INTERVAL} * * * * /data/data/com.termux/files/usr/bin/bash $HERE/run_sync.sh
EOF
crontab "$CRON_FILE"
echo "crontab installed:"; crontab -l

# 3) (Re)start crond.
pkill -x crond 2>/dev/null || true
sleep 1
crond
sleep 1
pgrep -a crond || { echo "ERROR: crond didn't start"; exit 3; }

# 4) Acquire the wake-lock now (next boot, the boot script will do it).
termux-wake-lock
echo "wake-lock acquired (Termux notification will show)"

cat <<EOM

Done. Schedule: every ${INTERVAL} min.
   tail -f ${LOG_DIR}/cron_ticks.log
   tail -f ${LOG_DIR}/sync.log

Reminder — to make this survive a reboot:
  * Tap the Termux:Boot app icon ONCE (it registers BOOT_COMPLETED).
  * Settings → Apps → Termux / Termux:API / Termux:Boot → Battery → Unrestricted.
EOM
