#!/usr/bin/env bash
# Offline tests for the JobScheduler setup path (no Termux / Android required).
# Run: bash test_jobscheduler_setup.sh
set -euo pipefail

ROOT="$(dirname "$(readlink -f "$0")")"
FAILS=0
assert() {
    if ! eval "$1"; then
        echo "FAIL: $2"
        echo "      cond: $1"
        FAILS=$((FAILS + 1))
    else
        echo "ok: $2"
    fi
}

WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

HOME_DIR="$WORKDIR/home"
BIN="$WORKDIR/bin"
STATE="$WORKDIR/state"
REPO="$WORKDIR/repo"
mkdir -p "$HOME_DIR/.config/hidock-sync" "$BIN" "$STATE" "$REPO"

cp "$ROOT/setup-jobscheduler.sh" "$ROOT/job_fire.sh" "$REPO/"
cat > "$REPO/run_sync.sh" <<'EOF'
#!/usr/bin/env bash
echo "RUN_SYNC args=$*"
exit 0
EOF
chmod +x "$REPO/setup-jobscheduler.sh" "$REPO/job_fire.sh" "$REPO/run_sync.sh"

cat > "$HOME_DIR/.config/hidock-sync/config" <<EOF
LOG_DIR=$HOME_DIR/.config/hidock-sync
CRON_INTERVAL_MIN=30
EOF

# Seed a hidock crontab plus an unrelated line so we prove we only strip ours.
printf '%s\n' \
    "# Generated by hidock-android-sync setup-cron.sh" \
    "*/30 * * * * /data/data/com.termux/files/usr/bin/bash /old/run_sync.sh" \
    "0 5 * * * /usr/bin/true" \
    > "$STATE/crontab"

cat > "$BIN/termux-job-scheduler" <<EOF
#!/usr/bin/env bash
echo "termux-job-scheduler \$*" >> "$STATE/tjs.log"
printf '%s\n' "\$@" > "$STATE/tjs.last_args"
if [ "\${1:-}" = "-p" ] || [ "\${1:-}" = "--pending" ]; then
    echo "Pending Job 834001: $REPO/job_fire.sh    (periodic: 1800000ms) (persisted)"
    exit 0
fi
if [ "\${1:-}" = "--cancel" ]; then
    echo "Cancelling Job 834001"
    exit 0
fi
echo "Scheduling Job 834001 - response 1"
exit 0
EOF
chmod +x "$BIN/termux-job-scheduler"

cat > "$BIN/crontab" <<EOF
#!/usr/bin/env bash
if [ "\${1:-}" = "-l" ]; then
    [ -f "$STATE/crontab" ] || exit 1
    cat "$STATE/crontab"
    exit 0
fi
if [ "\${1:-}" = "-r" ]; then
    rm -f "$STATE/crontab"
    exit 0
fi
if [ "\${1:-}" = "-" ]; then
    cat > "$STATE/crontab"
    exit 0
fi
if [ -n "\${1:-}" ]; then
    cat "\$1" > "$STATE/crontab"
    exit 0
fi
cat > "$STATE/crontab"
EOF
chmod +x "$BIN/crontab"

cat > "$BIN/pkill" <<EOF
#!/usr/bin/env bash
echo "pkill \$*" >> "$STATE/pkill.log"
exit 0
EOF
chmod +x "$BIN/pkill"

export HOME="$HOME_DIR"
export PATH="$BIN:$PATH"

echo "== setup-jobscheduler.sh (interval 30)"
bash "$REPO/setup-jobscheduler.sh"

assert "[ -f \"$STATE/tjs.last_args\" ]" "termux-job-scheduler was invoked"
ARGS="$(tr '\n' ' ' < "$STATE/tjs.last_args")"
# Last invocation may be -p; the schedule call is in tjs.log
assert "grep -q -- '--job-id 834001' \"$STATE/tjs.log\"" "fixed job-id 834001"
assert "grep -q -- '--period-ms 1800000' \"$STATE/tjs.log\"" "30 min → 1800000 ms"
assert "grep -q -- '--persisted true' \"$STATE/tjs.log\"" "persisted true"
assert "grep -q -- '--battery-not-low false' \"$STATE/tjs.log\"" "battery-not-low false"
assert "grep -q -- '--network any' \"$STATE/tjs.log\"" "network any"
assert "grep -q -- \"-s $REPO/job_fire.sh\" \"$STATE/tjs.log\"" "absolute wrapper path"
assert "grep -q 'pkill -x crond' \"$STATE/pkill.log\"" "crond stopped"
assert "grep -q '/usr/bin/true' \"$STATE/crontab\"" "unrelated crontab line kept"
assert "! grep -q run_sync.sh \"$STATE/crontab\"" "hidock crontab line removed"
assert "[ ! -f \"$HOME_DIR/.config/cron/crontab\" ]" "generated cron file removed"

BOOT="$HOME_DIR/.termux/boot/start-crond"
assert "[ -x \"$BOOT\" ]" "boot script replaced and executable"
assert "! grep -q '^crond' \"$BOOT\"" "boot script no longer starts crond"
assert "grep -q -- '--persisted true' \"$BOOT\"" "boot insurance re-asserts persisted job"
assert "grep -q -- '--job-id 834001' \"$BOOT\"" "boot insurance uses job 834001"
assert "grep -qi 'optional' \"$BOOT\"" "boot script documents optional insurance"

echo
echo "== setup is idempotent"
: > "$STATE/tjs.log"
: > "$STATE/pkill.log"
bash "$REPO/setup-jobscheduler.sh"
assert "grep -q -- '--job-id 834001' \"$STATE/tjs.log\"" "second run re-registers the job"

echo
echo "== interval below Android 15-min minimum is clamped"
sed -i 's/CRON_INTERVAL_MIN=30/CRON_INTERVAL_MIN=5/' "$HOME_DIR/.config/hidock-sync/config"
: > "$STATE/tjs.log"
bash "$REPO/setup-jobscheduler.sh"
assert "grep -q -- '--period-ms 900000' \"$STATE/tjs.log\"" "5 min clamped to 900000 ms"
assert "! grep -q -- '--period-ms 300000' \"$STATE/tjs.log\"" "did not schedule illegal 5-min period"

echo
echo "== setup-jobscheduler.sh --cancel"
: > "$STATE/tjs.log"
bash "$REPO/setup-jobscheduler.sh" --cancel
assert "grep -q -- '--cancel' \"$STATE/tjs.log\"" "cancel flag passed"
assert "grep -q -- '--job-id 834001' \"$STATE/tjs.log\"" "cancel targets job 834001"

echo
echo "== job_fire.sh writes JOB_FIRE and execs run_sync.sh"
TICK="$WORKDIR/ticks.txt"
OUT="$WORKDIR/job_fire.out"
JOB_TICK_FILE="$TICK" HOME="$HOME_DIR" bash "$REPO/job_fire.sh" --dry-run > "$OUT" 2>&1 || true
assert "grep -q '^JOB_FIRE ' \"$OUT\"" "JOB_FIRE line on stdout"
assert "grep -q '^JOB_FIRE ' \"$TICK\"" "JOB_FIRE appended to world-readable tick file"
assert "grep -q 'job-id=834001' \"$TICK\"" "tick names job 834001"
assert "grep -q 'boot_id=' \"$TICK\"" "tick includes boot_id"
assert "grep -q 'RUN_SYNC args=--dry-run' \"$OUT\"" "existing run_sync.sh was executed"
assert "grep -q '^JOB_FIRE ' \"$HOME_DIR/.config/hidock-sync/cron_ticks.log\"" "JOB_FIRE also appended to LOG_DIR"

echo
if [ "$FAILS" -ne 0 ]; then
    echo "$FAILS assertion(s) failed"
    echo "---- tjs.log ----"; cat "$STATE/tjs.log" || true
    echo "---- crontab ----"; cat "$STATE/crontab" || true
    echo "---- boot ----"; cat "$BOOT" || true
    echo "---- job_fire.out ----"; cat "$OUT" || true
    exit 1
fi
echo "All JobScheduler setup tests passed."
